export const GET_FETCH_POKEMON_START = "GET_FETCH_POKEMON_START";
export const GET_FETCH_POKEMON_SUCCESS = "GET_FETCH_POKEMON_SUCCESS";
export const GET_FETCH_POKEMON_ERROR = "GET_FETCH_POKEMON_ERROR";
export const RESET_LIST_POKEMON = "RESET_LIST_POKEMON";

export const GET_SELECT_POKEMON_START = "GET_SELECT_POKEMON_START";
export const GET_SELECT_POKEMON_SUCCESS = "GET_SELECT_POKEMON_SUCCESS";
export const GET_SELECT_POKEMON_ERROR = "GET_SELECT_POKEMON_ERROR   ";

export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const RESET_SELECTED_POKEMON = "RESET_SELECTED_POKEMON";

export const SET_COLOR_MODE = "SET_COLOR_MODE";
