export const GET_FETCH_POKEMON_START = "GET_FETCH_POKEMON_START";
export const GET_FETCH_POKEMON_SUCCESS = "GET_FETCH_POKEMON_SUCCESS";
export const GET_FETCH_POKEMON_ERROR = "GET_FETCH_POKEMON_ERROR";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
